[build]
  publish = "."

[[redirects]]
  from = "/operators"
  to = "/operators.html"
  status = 200

[[redirects]]
  from = "/the-science"
  to = "/index.html#science"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
